spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurante?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Configuração do Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true

# Inicialização SQL
  sql:
    init:
      schema-locations: classpath:/schema-mysql.sql
      mode: always
      platform: mysql
