# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/restaurante?createDatabaseIfNotExist=true
#     username: root
#     password: 
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     initialize: true
#   servlet:
#     multipart:
#       enabled: true
#       max-file-size: 10MB
#       max-request-size: 10MB

# # Configuração do Hibernate
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect
#         jdbc:
#           lob:
#             non_contextual_creation: true

# # Inicialização SQL
#   sql:
#     init:
#       schema-locations: classpath:/schema-mysql.sql
#       mode: always
#       platform: mysql

# Configuração do banco de dados
spring:
  datasource:
    url: jdbc:postgresql://dpg-cphqkoect0pc73fi8hgg-a.oregon-postgres.render.com:5432/restaurante_i0dq
    username: maria
    password: zYM7AAcjliQwJZi4Pq0Hnb3uazx32wJL
    driver-class-name: org.postgresql.Driver
    initialize: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Configuração do Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Inicialização SQL
  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgresql
